//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Nullable<System.DateTime> Duration { get; set; }
        public string Title { get; set; }
        public string Location { get; set; }
        public int Categories { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public string User { get; set; }
        public int ID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User1 { get; set; }
    }
}
